//! Wire types for OpenAI-compatible chat completions.
//!
//! Field names match the OpenAI schema (`role`, `content`, `tool_calls`,
//! `tool_call_id`, `function.arguments`) so the same struct serializes to
//! any compatible endpoint (vLLM, SGLang, llama.cpp server, commercial APIs).

use serde::{Deserialize, Deserializer, Serialize};

/// Message author role.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Role {
    System,
    User,
    Assistant,
    Tool,
}

/// A single message in the conversation.
///
/// `tool_calls` is populated on assistant turns that request tool execution.
/// `tool_call_id` is required on `Role::Tool` messages to associate the
/// result with the originating call.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Message {
    pub role: Role,

    /// MAY be empty string when the assistant only emits tool calls. Some
    /// providers reject `null` here, others reject empty string — we always
    /// send the field as a (possibly empty) string for portability.
    #[serde(default, deserialize_with = "deserialize_null_string")]
    pub content: String,

    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub tool_call_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub tool_calls: Option<Vec<ToolCall>>,
}

impl Message {
    pub fn system(content: impl Into<String>) -> Self {
        Self {
            role: Role::System,
            content: content.into(),
            tool_call_id: None,
            tool_calls: None,
        }
    }

    pub fn user(content: impl Into<String>) -> Self {
        Self {
            role: Role::User,
            content: content.into(),
            tool_call_id: None,
            tool_calls: None,
        }
    }

    pub fn assistant(content: impl Into<String>) -> Self {
        Self {
            role: Role::Assistant,
            content: content.into(),
            tool_call_id: None,
            tool_calls: None,
        }
    }

    /// Build a `tool` response message tied to a specific call ID.
    pub fn tool_result(tool_call_id: impl Into<String>, content: impl Into<String>) -> Self {
        Self {
            role: Role::Tool,
            content: content.into(),
            tool_call_id: Some(tool_call_id.into()),
            tool_calls: None,
        }
    }
}

fn deserialize_null_string<'de, D>(deserializer: D) -> Result<String, D::Error>
where
    D: Deserializer<'de>,
{
    Ok(Option::<String>::deserialize(deserializer)?.unwrap_or_default())
}

/// A single tool/function call emitted by the assistant.
///
/// `id` is generated by the model and MUST be echoed back in the matching
/// `Role::Tool` response so the model can correlate result to call.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ToolCall {
    pub id: String,

    /// Currently always `"function"` in the OpenAI schema; we serialize it
    /// for compatibility but ignore it on parse.
    #[serde(default = "default_tool_type", rename = "type")]
    pub call_type: String,

    pub function: FunctionCall,
}

fn default_tool_type() -> String {
    "function".into()
}

/// Function name + raw JSON argument string.
///
/// `arguments` is intentionally `String`, not a parsed value: streaming
/// chunks deliver arguments as concatenated string fragments that only form
/// valid JSON after the final delta. Callers parse with [`serde_json`] once
/// the full payload has been assembled.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct FunctionCall {
    pub name: String,
    pub arguments: String,
}

/// Chat completion request body.
///
/// Tool definitions are accepted as raw `serde_json::Value` so the agent
/// crate can keep them in a fixed alphabetical order (SPEC §3.6) without
/// this crate needing to know their schema.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatRequest {
    pub model: String,

    pub messages: Vec<Message>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub tools: Option<Vec<serde_json::Value>>,

    /// Per-request thinking budget (OpenAI's `max_completion_tokens`).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_completion_tokens: Option<u32>,

    /// Set to `true` for SSE streaming responses.
    pub stream: bool,

    /// Optional sampling temperature (0.0..=2.0). Most providers default to 1.0.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub temperature: Option<f32>,
}

impl ChatRequest {
    /// Convenience builder for non-streaming requests.
    pub fn new(model: impl Into<String>, messages: Vec<Message>) -> Self {
        Self {
            model: model.into(),
            messages,
            tools: None,
            max_completion_tokens: None,
            stream: false,
            temperature: None,
        }
    }
}

/// Token usage block reported by the server (when supported).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Usage {
    #[serde(default)]
    pub prompt_tokens: u32,
    #[serde(default)]
    pub completion_tokens: u32,
    #[serde(default)]
    pub total_tokens: u32,
}

/// Parsed result of a non-streaming completion, or the assembled result of
/// a streaming completion.
#[derive(Debug, Clone)]
pub struct ChatResponse {
    pub message: Message,
    pub usage: Option<Usage>,
    /// `finish_reason` reported by the server (`"stop"`, `"tool_calls"`,
    /// `"length"`, …) when present.
    pub finish_reason: Option<String>,
}

// ---------- internal wire types for deserialization ----------

#[derive(Debug, Deserialize)]
pub(crate) struct ChatCompletionResponse {
    pub choices: Vec<Choice>,
    #[serde(default)]
    pub usage: Option<Usage>,
}

#[derive(Debug, Deserialize)]
pub(crate) struct Choice {
    pub message: Message,
    #[serde(default)]
    pub finish_reason: Option<String>,
}
